import type { MonopolyBoardSlot } from './types';

/** 棋盘布局 SSOT：格子位置与引用的经济模板 */
export const MONOPOLY_BOARD_SLOTS: MonopolyBoardSlot[] = [
  { index: 0, name: '起点', country: '世界', type: 'start', propertyTemplateId: 'start-bonus' },
  { index: 1, name: '苏州', country: '华东', type: 'city', propertyTemplateId: 'city-green-a', colorGroup: 'green' },
  { index: 2, name: '财产税', country: '世界', type: 'tax', propertyTemplateId: 'tax-property' },
  { index: 3, name: '抚顺', country: '东北', type: 'city', propertyTemplateId: 'city-green-b', colorGroup: 'green' },
  { index: 4, name: '命运', country: '世界', type: 'fate' },
  { index: 5, name: '广州火车站', country: '交通', type: 'rail', propertyTemplateId: 'rail-standard' },
  { index: 6, name: '陕西', country: '西北', type: 'city', propertyTemplateId: 'city-gray-a', colorGroup: 'gray' },
  { index: 7, name: '机会', country: '世界', type: 'chance' },
  { index: 8, name: '甘肃', country: '西北', type: 'city', propertyTemplateId: 'city-gray-a', colorGroup: 'gray' },
  { index: 9, name: '澳门', country: '港澳', type: 'city', propertyTemplateId: 'city-gray-b', colorGroup: 'gray' },
  { index: 10, name: '进牢', country: '世界', type: 'jail' },
  { index: 11, name: '新疆', country: '西北', type: 'city', propertyTemplateId: 'city-blue-a', colorGroup: 'blue' },
  { index: 12, name: '自来水厂', country: '公用', type: 'utility', propertyTemplateId: 'utility-water' },
  { index: 13, name: '川西', country: '西南', type: 'city', propertyTemplateId: 'city-blue-b', colorGroup: 'blue' },
  { index: 14, name: '北湖', country: '西北', type: 'city', propertyTemplateId: 'city-blue-b', colorGroup: 'blue' },
  { index: 15, name: '沈阳火车站', country: '交通', type: 'rail', propertyTemplateId: 'rail-standard' },
  { index: 16, name: '常州', country: '华东', type: 'city', propertyTemplateId: 'city-red-a', colorGroup: 'red' },
  { index: 17, name: '机会', country: '世界', type: 'chance' },
  { index: 18, name: '苏南', country: '华东', type: 'city', propertyTemplateId: 'city-red-a', colorGroup: 'red' },
  { index: 19, name: '回牢', country: '世界', type: 'bonus' },
  { index: 20, name: '济南', country: '华东', type: 'city', propertyTemplateId: 'city-yellow-a', colorGroup: 'yellow' },
  { index: 21, name: '桂林', country: '华南', type: 'city', propertyTemplateId: 'city-yellow-a', colorGroup: 'yellow' },
  { index: 22, name: '机会', country: '世界', type: 'chance' },
  { index: 23, name: '哈尔滨', country: '东北', type: 'city', propertyTemplateId: 'city-yellow-b', colorGroup: 'yellow' },
  { index: 24, name: '吉林', country: '东北', type: 'city', propertyTemplateId: 'city-yellow-b', colorGroup: 'yellow' },
  { index: 25, name: '罚款停车站', country: '交通', type: 'rail', propertyTemplateId: 'rail-parking' },
  { index: 26, name: '长春', country: '东北', type: 'city', propertyTemplateId: 'city-purple-a', colorGroup: 'purple' },
  { index: 27, name: '命运', country: '世界', type: 'fate' },
  { index: 28, name: '庆阳', country: '西北', type: 'city', propertyTemplateId: 'city-purple-b', colorGroup: 'purple' },
  { index: 29, name: '深圳', country: '华南', type: 'city', propertyTemplateId: 'city-purple-b', colorGroup: 'purple' },
  { index: 30, name: '机场', country: '世界', type: 'bonus' },
  { index: 31, name: '成都', country: '西南', type: 'city', propertyTemplateId: 'city-red-b', colorGroup: 'red' },
  { index: 32, name: '所得税', country: '世界', type: 'tax', propertyTemplateId: 'tax-income' },
  { index: 33, name: '郑州火车站', country: '交通', type: 'rail', propertyTemplateId: 'rail-standard' },
  { index: 34, name: '北京', country: '华北', type: 'city', propertyTemplateId: 'city-pink-a', colorGroup: 'pink' },
  { index: 35, name: '机会', country: '世界', type: 'chance' },
  { index: 36, name: '上海', country: '华东', type: 'city', propertyTemplateId: 'city-pink-a', colorGroup: 'pink' },
  { index: 37, name: '命运', country: '世界', type: 'fate' },
  { index: 38, name: '苏州火车站', country: '交通', type: 'rail', propertyTemplateId: 'rail-standard' },
  { index: 39, name: '入牢', country: '世界', type: 'jail' },
];
