import type { CardDefinition } from '../../types/card';

export const EQUIPMENT_CARDS: CardDefinition[] = [
  {
    id: 'zhuge_liannu',
    name: '诸葛连弩',
    type: 'equipment',
    subType: 'weapon',
    description: '你可以额外使用任意张【杀】。',
    canInitiate: true,
    targeting: { selector: 'self' },
    effects: [{ action: 'equip', params: { slot: 'weapon', shaUnlimited: true } }],
  },
  {
    id: 'qinggang_jian',
    name: '青釭剑',
    type: 'equipment',
    subType: 'weapon',
    description: '你使用【杀】无视目标防具。',
    canInitiate: true,
    targeting: { selector: 'self' },
    effects: [{ action: 'equip', params: { slot: 'weapon', ignoreArmor: true } }],
  },
  {
    id: 'qinglong_yanyuedao',
    name: '青龙偃月刀',
    type: 'equipment',
    subType: 'weapon',
    description: '攻击范围3；你使用【杀】被闪抵消后可再对同目标使用一张【杀】。',
    canInitiate: true,
    targeting: { selector: 'self' },
    effects: [{ action: 'equip', params: { slot: 'weapon', range: 3 } }],
  },
  {
    id: 'zhangba_shemao',
    name: '丈八蛇矛',
    type: 'equipment',
    subType: 'weapon',
    description: '攻击范围3；你可以将两张手牌当【杀】使用。',
    canInitiate: true,
    targeting: { selector: 'self' },
    effects: [{ action: 'equip', params: { slot: 'weapon', range: 3, virtualSha: true } }],
  },
  {
    id: 'guanshi_fudao',
    name: '贯石斧',
    type: 'equipment',
    subType: 'weapon',
    description: '攻击范围3；【杀】被闪时可弃两张牌令此杀仍生效。',
    canInitiate: true,
    targeting: { selector: 'self' },
    effects: [{ action: 'equip', params: { slot: 'weapon', range: 3 } }],
  },
  {
    id: 'fangtian_huaji',
    name: '方天画戟',
    type: 'equipment',
    subType: 'weapon',
    description: '攻击范围4；你使用【杀】是最后一张手牌时可额外指定至多2名目标。',
    canInitiate: true,
    targeting: { selector: 'self' },
    effects: [{ action: 'equip', params: { slot: 'weapon', range: 4 } }],
  },
  {
    id: 'qilin_gong',
    name: '麒麟弓',
    type: 'equipment',
    subType: 'weapon',
    description: '攻击范围5；你使用【杀】对目标造成伤害时可弃置其坐骑。',
    canInitiate: true,
    targeting: { selector: 'self' },
    effects: [{ action: 'equip', params: { slot: 'weapon', range: 5 } }],
  },
  {
    id: 'renwang_dun',
    name: '仁王盾',
    type: 'equipment',
    subType: 'armor',
    description: '黑色【杀】对你无效。',
    canInitiate: true,
    targeting: { selector: 'self' },
    effects: [{ action: 'equip', params: { slot: 'armor', blockBlackSha: true } }],
  },
  {
    id: 'bagua_zhen',
    name: '八卦阵',
    type: 'equipment',
    subType: 'armor',
    description: '当你需要使用【闪】时，可判定：红色视为打出【闪】。',
    canInitiate: true,
    targeting: { selector: 'self' },
    effects: [{ action: 'equip', params: { slot: 'armor', judgeForShan: true } }],
  },
  {
    id: 'dilu',
    name: '的卢马',
    type: 'equipment',
    subType: 'horse_plus',
    description: '其他角色计算与你的距离+1。',
    canInitiate: true,
    targeting: { selector: 'self' },
    effects: [{ action: 'equip', params: { slot: 'horse_plus' } }],
  },
  {
    id: 'jueying',
    name: '绝影',
    type: 'equipment',
    subType: 'horse_plus',
    description: '其他角色计算与你的距离+1。',
    canInitiate: true,
    targeting: { selector: 'self' },
    effects: [{ action: 'equip', params: { slot: 'horse_plus' } }],
  },
  {
    id: 'chitu',
    name: '赤兔',
    type: 'equipment',
    subType: 'horse_minus',
    description: '你计算与其他角色的距离-1。',
    canInitiate: true,
    targeting: { selector: 'self' },
    effects: [{ action: 'equip', params: { slot: 'horse_minus' } }],
  },
  {
    id: 'dawan',
    name: '大宛',
    type: 'equipment',
    subType: 'horse_minus',
    description: '你计算与其他角色的距离-1。',
    canInitiate: true,
    targeting: { selector: 'self' },
    effects: [{ action: 'equip', params: { slot: 'horse_minus' } }],
  },
  {
    id: 'zixing',
    name: '紫骍',
    type: 'equipment',
    subType: 'horse_minus',
    description: '你计算与其他角色的距离-1。',
    canInitiate: true,
    targeting: { selector: 'self' },
    effects: [{ action: 'equip', params: { slot: 'horse_minus' } }],
  },
];
