import type { CardDefinition } from '../../types/card';

export const TRICK_CARDS: CardDefinition[] = [
  {
    id: 'guohe_chaiqiao',
    name: '过河拆桥',
    type: 'trick',
    subType: 'instant',
    description: '弃置目标角色区域内的一张牌。',
    canInitiate: true,
    targeting: {
      selector: 'choose',
      count: { min: 1, max: 1 },
      filter: { relation: ['other'], alive: true },
      range: { type: 'unlimited' },
    },
    effects: [{ action: 'discard', params: { zone: 'any', count: 1 } }],
  },
  {
    id: 'shunshou_qianyang',
    name: '顺手牵羊',
    type: 'trick',
    subType: 'instant',
    description: '获得距离1以内的一名其他角色区域内的一张牌。',
    canInitiate: true,
    targeting: {
      selector: 'choose',
      count: { min: 1, max: 1 },
      filter: { relation: ['other'], alive: true },
      range: { type: 'fixed', value: 1 },
    },
    effects: [{ action: 'moveCard', params: { to: 'hand', count: 1 } }],
  },
  {
    id: 'wuzhongshengyou',
    name: '无中生有',
    type: 'trick',
    subType: 'instant',
    description: '摸两张牌。',
    canInitiate: true,
    targeting: { selector: 'self' },
    effects: [{ action: 'draw', params: { count: 2 } }],
  },
  {
    id: 'juedou',
    name: '决斗',
    type: 'trick',
    subType: 'damage',
    description: '与目标轮流打出【杀】，先不出者受到1点伤害。',
    canInitiate: true,
    targeting: {
      selector: 'choose',
      count: { min: 1, max: 1 },
      filter: { relation: ['other'], alive: true },
      range: { type: 'unlimited' },
    },
    effects: [
      {
        action: 'promptResponse',
        params: { responseType: 'sha', alternate: true, onFail: [{ action: 'damage', params: { amount: 1 } }] },
      },
    ],
  },
  {
    id: 'nanman_ruqin',
    name: '南蛮入侵',
    type: 'trick',
    subType: 'aoe',
    description: '所有其他角色须打出【杀】，否则受到1点伤害。',
    canInitiate: true,
    targeting: { selector: 'allOthers' },
    effects: [
      {
        action: 'promptResponse',
        params: { responseType: 'sha', aoe: true, onFail: [{ action: 'damage', params: { amount: 1 } }] },
      },
    ],
  },
  {
    id: 'wanjian_qifa',
    name: '万箭齐发',
    type: 'trick',
    subType: 'aoe',
    description: '所有其他角色须打出【闪】，否则受到1点伤害。',
    canInitiate: true,
    targeting: { selector: 'allOthers' },
    effects: [
      {
        action: 'promptResponse',
        params: { responseType: 'shan', aoe: true, onFail: [{ action: 'damage', params: { amount: 1 } }] },
      },
    ],
  },
  {
    id: 'taoyuan_jieyi',
    name: '桃园结义',
    type: 'trick',
    subType: 'instant',
    description: '所有角色各回复1点体力。',
    canInitiate: true,
    targeting: { selector: 'all' },
    effects: [{ action: 'recover', params: { amount: 1, all: true } }],
  },
  {
    id: 'wuxie_keji',
    name: '无懈可击',
    type: 'trick',
    subType: 'instant',
    description: '抵消一张锦囊牌的效果。',
    canInitiate: false,
    targeting: { selector: 'none' },
    effects: [],
    responseTo: ['wuxie'],
  },
  {
    id: 'lebusishu',
    name: '乐不思蜀',
    type: 'trick',
    subType: 'delay',
    description: '置于目标判定区；判定不为♥则跳过出牌阶段。',
    canInitiate: true,
    targeting: {
      selector: 'choose',
      count: { min: 1, max: 1 },
      filter: { relation: ['other'], alive: true },
      range: { type: 'unlimited' },
      canCancel: false,
    },
    effects: [{ action: 'judge', params: { placeInJudge: true, skipPhase: 'play' } }],
    judgeSuccess: { suit: ['heart'] },
  },
  {
    id: 'shandian',
    name: '闪电',
    type: 'trick',
    subType: 'delay',
    description: '置于自己判定区；判定为黑桃2~9则受到3点雷电伤害。',
    canInitiate: true,
    targeting: { selector: 'self' },
    effects: [{ action: 'judge', params: { placeInJudge: true, damageOnFail: 3 } }],
    judgeSuccess: { suit: ['spade'], color: 'black' },
  },
  {
    id: 'bingliangsunduan',
    name: '兵粮寸断',
    type: 'trick',
    subType: 'delay',
    description: '置于距离1以内其他角色判定区；判定不为♣则跳过摸牌阶段。',
    canInitiate: true,
    targeting: {
      selector: 'choose',
      count: { min: 1, max: 1 },
      filter: { relation: ['other'], alive: true },
      range: { type: 'fixed', value: 1 },
    },
    effects: [{ action: 'judge', params: { placeInJudge: true, skipPhase: 'draw' } }],
    judgeSuccess: { suit: ['club'] },
  },
];
