/**
 * 契约错误码枚举（对齐 design/api-contract.v1.md §0.4）
 * server 与 client 都可以引用。
 */
export const ErrorCodes = {
  UNAUTHORIZED: 'E_UNAUTHORIZED',
  FORBIDDEN: 'E_FORBIDDEN',
  BAD_CREDENTIALS: 'E_BAD_CREDENTIALS',
  USER_EXISTS: 'E_USER_EXISTS',
  INVALID_EMAIL: 'E_INVALID_EMAIL',
  WEAK_PASSWORD: 'E_WEAK_PASSWORD',
  PASSWORD_MISMATCH: 'E_PASSWORD_MISMATCH',
  REFRESH_EXPIRED: 'E_REFRESH_EXPIRED',
  REFRESH_REUSED: 'E_REFRESH_REUSED',
  LOGIN_RATE_LIMIT: 'E_LOGIN_RATE_LIMIT',
  ROOM_NOT_FOUND: 'E_ROOM_NOT_FOUND',
  ROOM_FULL: 'E_ROOM_FULL',
  ROOM_STARTED: 'E_ROOM_STARTED',
  ROOM_VERSION_MISMATCH: 'E_ROOM_VERSION_MISMATCH',
  VERSION_UNKNOWN: 'E_VERSION_UNKNOWN',
  CHAT_RATE_LIMIT: 'E_CHAT_RATE_LIMIT',
  CHAT_TOO_LONG: 'E_CHAT_TOO_LONG',
  CHAT_MUTED: 'E_CHAT_MUTED',
  SANDBOX_DISABLED: 'E_SANDBOX_DISABLED',
  INTERNAL: 'E_INTERNAL',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
