import type { LianliankanConfig } from '@tk/shared';

export const LIANLIANKAN_CONFIG: LianliankanConfig = {
  defaultThemeId: 'fruits',
  defaultDifficultyId: 'easy',
  themes: [
    {
      themeId: 'fruits',
      name: '果蔬',
      items: [
        { id: 'apple', text: '苹果', emoji: '🍎', similarGroup: 'red' },
        { id: 'cherry', text: '樱桃', emoji: '🍒', similarGroup: 'red' },
        { id: 'strawberry', text: '草莓', emoji: '🍓', similarGroup: 'red' },
        { id: 'banana', text: '香蕉', emoji: '🍌', similarGroup: 'yellow' },
        { id: 'lemon', text: '柠檬', emoji: '🍋', similarGroup: 'yellow' },
        { id: 'corn', text: '玉米', emoji: '🌽', similarGroup: 'yellow' },
        { id: 'pear', text: '梨子', emoji: '🍐', similarGroup: 'green' },
        { id: 'kiwi', text: '猕猴桃', emoji: '🥝', similarGroup: 'green' },
        { id: 'grape', text: '葡萄', emoji: '🍇', similarGroup: 'purple' },
        { id: 'eggplant', text: '茄子', emoji: '🍆', similarGroup: 'purple' },
        { id: 'peach', text: '桃子', emoji: '🍑' },
        { id: 'watermelon', text: '西瓜', emoji: '🍉' },
      ],
      similarGroups: [
        { groupId: 'red', itemIds: ['apple', 'cherry', 'strawberry'] },
        { groupId: 'yellow', itemIds: ['banana', 'lemon', 'corn'] },
        { groupId: 'green', itemIds: ['pear', 'kiwi'] },
        { groupId: 'purple', itemIds: ['grape', 'eggplant'] },
      ],
    },
    {
      themeId: 'generals',
      name: '三国武将',
      items: [
        { id: 'liubei', text: '刘备', emoji: '仁', similarGroup: 'shu' },
        { id: 'guanyu', text: '关羽', emoji: '义', similarGroup: 'shu' },
        { id: 'zhangfei', text: '张飞', emoji: '勇', similarGroup: 'shu' },
        { id: 'caocao', text: '曹操', emoji: '魏', similarGroup: 'wei' },
        { id: 'xiahoudun', text: '夏侯惇', emoji: '刚', similarGroup: 'wei' },
        { id: 'zhangliao', text: '张辽', emoji: '突', similarGroup: 'wei' },
        { id: 'sunquan', text: '孙权', emoji: '吴', similarGroup: 'wu' },
        { id: 'zhouyu', text: '周瑜', emoji: '火', similarGroup: 'wu' },
        { id: 'luxun', text: '陆逊', emoji: '连', similarGroup: 'wu' },
        { id: 'lvbu', text: '吕布', emoji: '猛', similarGroup: 'qun' },
        { id: 'diaochan', text: '貂蝉', emoji: '离', similarGroup: 'qun' },
        { id: 'huatuo', text: '华佗', emoji: '医', similarGroup: 'qun' },
      ],
      similarGroups: [
        { groupId: 'shu', itemIds: ['liubei', 'guanyu', 'zhangfei'] },
        { groupId: 'wei', itemIds: ['caocao', 'xiahoudun', 'zhangliao'] },
        { groupId: 'wu', itemIds: ['sunquan', 'zhouyu', 'luxun'] },
        { groupId: 'qun', itemIds: ['lvbu', 'diaochan', 'huatuo'] },
      ],
    },
    {
      themeId: 'office',
      name: '办公用品',
      items: [
        { id: 'sheet', text: '表格', emoji: '表', similarGroup: 'file' },
        { id: 'doc', text: '文档', emoji: '文', similarGroup: 'file' },
        { id: 'slide', text: '幻灯', emoji: '演', similarGroup: 'file' },
        { id: 'pen', text: '钢笔', emoji: '笔', similarGroup: 'tool' },
        { id: 'pencil', text: '铅笔', emoji: '铅', similarGroup: 'tool' },
        { id: 'ruler', text: '直尺', emoji: '尺', similarGroup: 'tool' },
        { id: 'folder', text: '文件夹', emoji: '夹', similarGroup: 'storage' },
        { id: 'box', text: '档案盒', emoji: '盒', similarGroup: 'storage' },
        { id: 'clip', text: '回形针', emoji: '针', similarGroup: 'small' },
        { id: 'staple', text: '订书机', emoji: '订', similarGroup: 'small' },
        { id: 'calendar', text: '日历', emoji: '历' },
        { id: 'printer', text: '打印机', emoji: '印' },
      ],
      similarGroups: [
        { groupId: 'file', itemIds: ['sheet', 'doc', 'slide'] },
        { groupId: 'tool', itemIds: ['pen', 'pencil', 'ruler'] },
        { groupId: 'storage', itemIds: ['folder', 'box'] },
        { groupId: 'small', itemIds: ['clip', 'staple'] },
      ],
    },
    {
      themeId: 'kaomoji',
      name: '颜文字',
      items: [
        { id: 'smile', text: '开心', emoji: '(^_^)', similarGroup: 'happy' },
        { id: 'laugh', text: '大笑', emoji: '(≧▽≦)', similarGroup: 'happy' },
        { id: 'wink', text: '眨眼', emoji: '(^_~)', similarGroup: 'happy' },
        { id: 'sad', text: '难过', emoji: '(T_T)', similarGroup: 'sad' },
        { id: 'cry', text: '哭泣', emoji: '(；д；)', similarGroup: 'sad' },
        { id: 'shock', text: '震惊', emoji: '(⊙_⊙)', similarGroup: 'wow' },
        { id: 'blank', text: '呆住', emoji: '(・_・)', similarGroup: 'wow' },
        { id: 'table', text: '掀桌', emoji: '(╯°□°）╯', similarGroup: 'action' },
        { id: 'shrug', text: '摊手', emoji: '¯\\_(ツ)_/¯', similarGroup: 'action' },
        { id: 'spark', text: '闪亮', emoji: '✧٩(ˊωˋ*)و✧' },
        { id: 'sleep', text: '睡觉', emoji: '(-_-)zzz' },
        { id: 'run', text: '冲刺', emoji: 'ε=ε=┌(;￣◇￣)┘' },
        { id: 'hide', text: '躲藏', emoji: '|ω・）' },
        { id: 'angry', text: '生气', emoji: '(｀へ´)' },
      ],
      similarGroups: [
        { groupId: 'happy', itemIds: ['smile', 'laugh', 'wink'] },
        { groupId: 'sad', itemIds: ['sad', 'cry'] },
        { groupId: 'wow', itemIds: ['shock', 'blank'] },
        { groupId: 'action', itemIds: ['table', 'shrug'] },
      ],
    },
    {
      themeId: 'emoji-faces',
      name: 'Emoji表情',
      items: [
        { id: 'grin', text: '咧嘴', emoji: '😀', similarGroup: 'smile' },
        { id: 'joy', text: '笑哭', emoji: '😂', similarGroup: 'smile' },
        { id: 'halo', text: '天使', emoji: '😇', similarGroup: 'smile' },
        { id: 'heart', text: '喜欢', emoji: '😍', similarGroup: 'love' },
        { id: 'kiss', text: '飞吻', emoji: '😘', similarGroup: 'love' },
        { id: 'think', text: '思考', emoji: '🤔', similarGroup: 'mind' },
        { id: 'nerd', text: '学霸', emoji: '🤓', similarGroup: 'mind' },
        { id: 'party', text: '庆祝', emoji: '🥳', similarGroup: 'event' },
        { id: 'cool', text: '墨镜', emoji: '😎', similarGroup: 'style' },
        { id: 'cold', text: '冷', emoji: '🥶', similarGroup: 'weather' },
        { id: 'hot', text: '热', emoji: '🥵', similarGroup: 'weather' },
        { id: 'robot', text: '机器人', emoji: '🤖' },
        { id: 'ghost', text: '幽灵', emoji: '👻' },
        { id: 'alien', text: '外星', emoji: '👽' },
      ],
      similarGroups: [
        { groupId: 'smile', itemIds: ['grin', 'joy', 'halo'] },
        { groupId: 'love', itemIds: ['heart', 'kiss'] },
        { groupId: 'mind', itemIds: ['think', 'nerd'] },
        { groupId: 'weather', itemIds: ['cold', 'hot'] },
      ],
    },
  ],
  difficulties: [
    { difficultyId: 'easy', name: '简单', rows: 8, cols: 8, kindCount: 12, timeLimitSec: 210, entryFee: 5, rewardCoins: 10, similarGroupWeight: 0.16 },
    { difficultyId: 'normal', name: '普通', rows: 10, cols: 10, kindCount: 20, timeLimitSec: 180, entryFee: 5, rewardCoins: 18, similarGroupWeight: 0.38 },
    { difficultyId: 'hard', name: '困难', rows: 12, cols: 12, kindCount: 30, timeLimitSec: 150, entryFee: 5, rewardCoins: 32, similarGroupWeight: 0.62 },
  ],
  _v: 1,
};
