import type { LianliankanConfig } from '@tk/shared';

export const LIANLIANKAN_CONFIG: LianliankanConfig = {
  defaultThemeId: 'fruits',
  defaultDifficultyId: 'easy',
  themes: [
    {
      themeId: 'fruits',
      name: '果蔬',
      items: [
        { id: 'apple', text: '苹果', emoji: '🍎', similarGroup: 'red' },
        { id: 'cherry', text: '樱桃', emoji: '🍒', similarGroup: 'red' },
        { id: 'strawberry', text: '草莓', emoji: '🍓', similarGroup: 'red' },
        { id: 'banana', text: '香蕉', emoji: '🍌', similarGroup: 'yellow' },
        { id: 'lemon', text: '柠檬', emoji: '🍋', similarGroup: 'yellow' },
        { id: 'corn', text: '玉米', emoji: '🌽', similarGroup: 'yellow' },
        { id: 'pear', text: '梨子', emoji: '🍐', similarGroup: 'green' },
        { id: 'kiwi', text: '猕猴桃', emoji: '🥝', similarGroup: 'green' },
        { id: 'grape', text: '葡萄', emoji: '🍇', similarGroup: 'purple' },
        { id: 'eggplant', text: '茄子', emoji: '🍆', similarGroup: 'purple' },
        { id: 'peach', text: '桃子', emoji: '🍑' },
        { id: 'watermelon', text: '西瓜', emoji: '🍉' },
      ],
      similarGroups: [
        { groupId: 'red', itemIds: ['apple', 'cherry', 'strawberry'] },
        { groupId: 'yellow', itemIds: ['banana', 'lemon', 'corn'] },
        { groupId: 'green', itemIds: ['pear', 'kiwi'] },
        { groupId: 'purple', itemIds: ['grape', 'eggplant'] },
      ],
    },
    {
      themeId: 'generals',
      name: '三国武将',
      items: [
        { id: 'liubei', text: '刘备', emoji: '仁', similarGroup: 'shu' },
        { id: 'guanyu', text: '关羽', emoji: '义', similarGroup: 'shu' },
        { id: 'zhangfei', text: '张飞', emoji: '勇', similarGroup: 'shu' },
        { id: 'caocao', text: '曹操', emoji: '魏', similarGroup: 'wei' },
        { id: 'xiahoudun', text: '夏侯惇', emoji: '刚', similarGroup: 'wei' },
        { id: 'zhangliao', text: '张辽', emoji: '突', similarGroup: 'wei' },
        { id: 'sunquan', text: '孙权', emoji: '吴', similarGroup: 'wu' },
        { id: 'zhouyu', text: '周瑜', emoji: '火', similarGroup: 'wu' },
        { id: 'luxun', text: '陆逊', emoji: '连', similarGroup: 'wu' },
        { id: 'lvbu', text: '吕布', emoji: '猛', similarGroup: 'qun' },
        { id: 'diaochan', text: '貂蝉', emoji: '离', similarGroup: 'qun' },
        { id: 'huatuo', text: '华佗', emoji: '医', similarGroup: 'qun' },
      ],
      similarGroups: [
        { groupId: 'shu', itemIds: ['liubei', 'guanyu', 'zhangfei'] },
        { groupId: 'wei', itemIds: ['caocao', 'xiahoudun', 'zhangliao'] },
        { groupId: 'wu', itemIds: ['sunquan', 'zhouyu', 'luxun'] },
        { groupId: 'qun', itemIds: ['lvbu', 'diaochan', 'huatuo'] },
      ],
    },
    {
      themeId: 'office',
      name: '办公用品',
      items: [
        { id: 'sheet', text: '电脑', emoji: '💻', similarGroup: 'file' },
        { id: 'doc', text: '鼠标', emoji: '🖱', similarGroup: 'file' },
        { id: 'slide', text: '键盘', emoji: '⌨️', similarGroup: 'file' },
        { id: 'pen', text: '钢笔', emoji: '✒️', similarGroup: 'tool' },
        { id: 'pencil', text: '铅笔', emoji: '✏️', similarGroup: 'tool' },
        { id: 'ruler', text: '直尺', emoji: '📏', similarGroup: 'tool' },
        { id: 'folder', text: '文件夹', emoji: '📂', similarGroup: 'storage' },
        { id: 'box', text: '档案盒', emoji: '📦', similarGroup: 'storage' },
        { id: 'clip', text: '回形针', emoji: '📎', similarGroup: 'small' },
        { id: 'staple', text: '书本', emoji: '📚', similarGroup: 'small' },
        { id: 'calendar', text: '日历', emoji: '🗓' },
        { id: 'phone', text: '手机', emoji: '📱' },
      ],
      similarGroups: [
        { groupId: 'file', itemIds: ['sheet', 'doc', 'slide'] },
        { groupId: 'tool', itemIds: ['pen', 'pencil', 'ruler'] },
        { groupId: 'storage', itemIds: ['folder', 'box'] },
        { groupId: 'small', itemIds: ['clip', 'staple'] },
      ],
    },
    {
      themeId: 'kaomoji',
      name: '颜文字',
      items: [
        { id: 'smile', text: '开心', emoji: '(^_^)', similarGroup: 'happy' },
        { id: 'laugh', text: '大笑', emoji: '(≧▽≦)', similarGroup: 'happy' },
        { id: 'wink', text: '眨眼', emoji: '(^_~)', similarGroup: 'happy' },
        { id: 'sad', text: '难过', emoji: '(T_T)', similarGroup: 'sad' },
        { id: 'cry', text: '哭泣', emoji: '(；д；)', similarGroup: 'sad' },
        { id: 'shock', text: '震惊', emoji: '(⊙_⊙)', similarGroup: 'wow' },
        { id: 'blank', text: '呆住', emoji: '(・_・)', similarGroup: 'wow' },
        { id: 'table', text: '掀桌', emoji: '(╯°□°）╯', similarGroup: 'action' },
        { id: 'shrug', text: '摊手', emoji: '¯\\_(ツ)_/¯', similarGroup: 'action' },
        { id: 'spark', text: '闪亮', emoji: '✧٩(ˊωˋ*)و✧' },
        { id: 'sleep', text: '睡觉', emoji: '(-_-)zzz' },
        { id: 'run', text: '冲刺', emoji: 'ε=ε=┌(;￣◇￣)┘' },
        { id: 'hide', text: '躲藏', emoji: '|ω・）' },
        { id: 'angry', text: '生气', emoji: '(｀へ´)' },
      ],
      similarGroups: [
        { groupId: 'happy', itemIds: ['smile', 'laugh', 'wink'] },
        { groupId: 'sad', itemIds: ['sad', 'cry'] },
        { groupId: 'wow', itemIds: ['shock', 'blank'] },
        { groupId: 'action', itemIds: ['table', 'shrug'] },
      ],
    },
    {
      themeId: 'emoji-faces',
      name: 'Emoji表情',
      items: [
        { id: 'grin', text: '咧嘴', emoji: '😀', similarGroup: 'smile' },
        { id: 'joy', text: '笑哭', emoji: '😂', similarGroup: 'smile' },
        { id: 'halo', text: '天使', emoji: '😇', similarGroup: 'smile' },
        { id: 'heart', text: '喜欢', emoji: '😍', similarGroup: 'love' },
        { id: 'kiss', text: '飞吻', emoji: '😘', similarGroup: 'love' },
        { id: 'think', text: '思考', emoji: '🤔', similarGroup: 'mind' },
        { id: 'nerd', text: '学霸', emoji: '🤓', similarGroup: 'mind' },
        { id: 'party', text: '庆祝', emoji: '🥳', similarGroup: 'event' },
        { id: 'cool', text: '墨镜', emoji: '😎', similarGroup: 'style' },
        { id: 'cold', text: '冷', emoji: '🥶', similarGroup: 'weather' },
        { id: 'hot', text: '热', emoji: '🥵', similarGroup: 'weather' },
        { id: 'robot', text: '机器人', emoji: '🤖' },
        { id: 'ghost', text: '幽灵', emoji: '👻' },
        { id: 'alien', text: '外星', emoji: '👽' },
      ],
      similarGroups: [
        { groupId: 'smile', itemIds: ['grin', 'joy', 'halo'] },
        { groupId: 'love', itemIds: ['heart', 'kiss'] },
        { groupId: 'mind', itemIds: ['think', 'nerd'] },
        { groupId: 'weather', itemIds: ['cold', 'hot'] },
      ],
    },
    {
      themeId: 'animals',
      name: '动物',
      items: [
        { id: 'cat', text: '猫', emoji: '🐱', similarGroup: 'pet' },
        { id: 'dog', text: '狗', emoji: '🐶', similarGroup: 'pet' },
        { id: 'rabbit', text: '兔', emoji: '🐰', similarGroup: 'pet' },
        { id: 'bear', text: '熊', emoji: '🐻', similarGroup: 'wild' },
        { id: 'tiger', text: '虎', emoji: '🐯', similarGroup: 'wild' },
        { id: 'lion', text: '狮', emoji: '🦁', similarGroup: 'wild' },
        { id: 'elephant', text: '象', emoji: '🐘', similarGroup: 'large' },
        { id: 'giraffe', text: '长颈鹿', emoji: '🦒', similarGroup: 'large' },
        { id: 'monkey', text: '猴', emoji: '🐵', similarGroup: 'playful' },
        { id: 'panda', text: '熊猫', emoji: '🐼', similarGroup: 'playful' },
        { id: 'cow', text: '牛', emoji: '🐮', similarGroup: 'farm' },
        { id: 'pig', text: '猪', emoji: '🐷', similarGroup: 'farm' },
        { id: 'chicken', text: '鸡', emoji: '🐔', similarGroup: 'farm' },
        { id: 'sheep', text: '羊', emoji: '🐑', similarGroup: 'farm' },
        { id: 'dragon', text: '龙', emoji: '🐲', similarGroup: 'mythical' },
        { id: 'phoenix', text: '凤凰', emoji: '🦅', similarGroup: 'mythical' },
        { id: 'unicorn', text: '独角兽', emoji: '🦄', similarGroup: 'mythical' },
        { id: 'mermaid', text: '美人鱼', emoji: '🧜‍♀️', similarGroup: 'mythical' },
      ],
      similarGroups: [
        { groupId: 'pet', itemIds: ['cat', 'dog', 'rabbit'] },
        { groupId: 'wild', itemIds: ['bear', 'tiger', 'lion'] },
        { groupId: 'large', itemIds: ['elephant', 'giraffe'] },
        { groupId: 'farm', itemIds: ['cow', 'pig', 'chicken'] },
        { groupId: 'mythical', itemIds: ['dragon'] },
      ],
    },
    {
      themeId: 'characters',
      name: '职业',
      items: [
        { id: 'student', text: '学生', emoji: '🧑‍🎓', similarGroup: 'school' },
        { id: 'teacher', text: '老师', emoji: '🧑‍🏫', similarGroup: 'school' },
        { id: 'doctor', text: '医生', emoji: '🧑‍⚕️', similarGroup: 'service' },
        { id: 'nurse', text: '护士', emoji: '👩‍⚕️', similarGroup: 'service' },
        { id: 'police', text: '警察', emoji: '👮', similarGroup: 'guard' },
        { id: 'firefighter', text: '消防员', emoji: '👨‍🚒', similarGroup: 'guard' },
        { id: 'chef', text: '厨师', emoji: '👨‍🍳', similarGroup: 'work' },
        { id: 'farmer', text: '农民', emoji: '👨‍🌾', similarGroup: 'work' },
        { id: 'artist', text: '画家', emoji: '👨‍🎨', similarGroup: 'creative' },
        { id: 'singer', text: '歌手', emoji: '🧑‍🎤', similarGroup: 'creative' },
        { id: 'astronaut', text: '宇航员', emoji: '🧑‍🚀', similarGroup: 'hero' },
        { id: 'athlete', text: '球员', emoji: '🏃', similarGroup: 'hero' },
        { id: 'wizard', text: '法师', emoji: '🧙' },
        { id: 'fairy', text: '仙女', emoji: '🧚' },
      ],
      similarGroups: [
        { groupId: 'school', itemIds: ['student', 'teacher'] },
        { groupId: 'service', itemIds: ['doctor', 'nurse'] },
        { groupId: 'guard', itemIds: ['police', 'firefighter'] },
        { groupId: 'work', itemIds: ['chef', 'farmer'] },
      ],
    },
    {
      themeId: 'objects',
      name: '物品',
      items: [
        { id: 'phone', text: '手机', emoji: '📱', similarGroup: 'digital' },
        { id: 'laptop', text: '电脑', emoji: '💻', similarGroup: 'digital' },
        { id: 'camera', text: '相机', emoji: '📷', similarGroup: 'digital' },
        { id: 'key', text: '钥匙', emoji: '🔑', similarGroup: 'daily' },
        { id: 'umbrella', text: '雨伞', emoji: '☂️', similarGroup: 'daily' },
        { id: 'glasses', text: '眼镜', emoji: '👓', similarGroup: 'daily' },
        { id: 'watch', text: '手表', emoji: '⌚', similarGroup: 'wear' },
        { id: 'bag', text: '背包', emoji: '🎒', similarGroup: 'wear' },
        { id: 'book', text: '书本', emoji: '📚', similarGroup: 'study' },
        { id: 'bulb', text: '灯泡', emoji: '💡', similarGroup: 'study' },
        { id: 'scissors', text: '剪刀', emoji: '✂️', similarGroup: 'tool' },
        { id: 'hammer', text: '锤子', emoji: '🔨', similarGroup: 'tool' },
        { id: 'gift', text: '礼物', emoji: '🎁' },
        { id: 'balloon', text: '气球', emoji: '🎈' },
      ],
      similarGroups: [
        { groupId: 'digital', itemIds: ['phone', 'laptop', 'camera'] },
        { groupId: 'daily', itemIds: ['key', 'umbrella', 'glasses'] },
        { groupId: 'wear', itemIds: ['watch', 'bag'] },
        { groupId: 'tool', itemIds: ['scissors', 'hammer'] },
      ],
    },
    {
      themeId: 'food',
      name: '食物',
      items: [
        { id: 'rice', text: '米饭', emoji: '🍚', similarGroup: 'staple' },
        { id: 'noodles', text: '面条', emoji: '🍜', similarGroup: 'staple' },
        { id: 'dumpling', text: '饺子', emoji: '🥟', similarGroup: 'staple' },
        { id: 'beer', text: '啤酒', emoji: '🍺', similarGroup: 'staple' },
        { id: 'burger', text: '汉堡', emoji: '🍔', similarGroup: 'fast' },
        { id: 'fries', text: '薯条', emoji: '🍟', similarGroup: 'fast' },
        { id: 'pizza', text: '披萨', emoji: '🍕', similarGroup: 'western' },
        { id: 'hotdog', text: '热狗', emoji: '🌭', similarGroup: 'western' },
        { id: 'sushi', text: '寿司', emoji: '🍣', similarGroup: 'japanese' },
        { id: 'bento', text: '便当', emoji: '🍱', similarGroup: 'japanese' },
        { id: 'cake', text: '蛋糕', emoji: '🍰', similarGroup: 'dessert' },
        { id: 'icecream', text: '冰淇淋', emoji: '🍦', similarGroup: 'dessert' },
        { id: 'hotpot', text: '火锅', emoji: '🍲' },
        { id: 'friedchicken', text: '炸鸡', emoji: '🍗' },
      ],
      similarGroups: [
        { groupId: 'staple', itemIds: ['rice', 'noodles', 'dumpling'] },
        { groupId: 'fast', itemIds: ['burger', 'fries'] },
        { groupId: 'western', itemIds: ['pizza', 'hotdog'] },
        { groupId: 'dessert', itemIds: ['cake', 'icecream'] },
      ],
    },
    {
      themeId: 'vegetables',
      name: '蔬菜',
      items: [
        { id: 'cabbage', text: '白菜', emoji: '🥬', similarGroup: 'leafy' },
        { id: 'lettuce', text: '生菜', emoji: '🥬', similarGroup: 'leafy' },
        { id: 'spinach', text: '菠菜', emoji: '🥬', similarGroup: 'leafy' },
        { id: 'carrot', text: '胡萝卜', emoji: '🥕', similarGroup: 'root' },
        { id: 'potato', text: '土豆', emoji: '🥔', similarGroup: 'root' },
        { id: 'onion', text: '洋葱', emoji: '🧅', similarGroup: 'root' },
        { id: 'broccoli', text: '西兰花', emoji: '🥦', similarGroup: 'green' },
        { id: 'cucumber', text: '黄瓜', emoji: '🥒', similarGroup: 'green' },
        { id: 'pepper', text: '辣椒', emoji: '🌶️', similarGroup: 'spicy' },
        { id: 'garlic', text: '大蒜', emoji: '🧄', similarGroup: 'spicy' },
        { id: 'mushroom', text: '蘑菇', emoji: '🍄', similarGroup: 'fungi' },
        { id: 'cornveg', text: '玉米', emoji: '🌽', similarGroup: 'fungi' },
        { id: 'tomato', text: '番茄', emoji: '🍅' },
        { id: 'eggplantveg', text: '茄子', emoji: '🍆' },
      ],
      similarGroups: [
        { groupId: 'leafy', itemIds: ['cabbage', 'lettuce', 'spinach'] },
        { groupId: 'root', itemIds: ['carrot', 'potato', 'onion'] },
        { groupId: 'green', itemIds: ['broccoli', 'cucumber'] },
        { groupId: 'spicy', itemIds: ['pepper', 'garlic'] },
      ],
    },
  ],
  difficulties: [
    { difficultyId: 'easy', name: '简单', rows: 8, cols: 8, kindCount: 12, timeLimitSec: 210, entryFee: 5, rewardCoins: 10, similarGroupWeight: 0.16 },
    { difficultyId: 'normal', name: '普通', rows: 10, cols: 10, kindCount: 20, timeLimitSec: 180, entryFee: 5, rewardCoins: 18, similarGroupWeight: 0.38 },
    { difficultyId: 'hard', name: '困难', rows: 12, cols: 12, kindCount: 30, timeLimitSec: 190, entryFee: 5, rewardCoins: 32, similarGroupWeight: 0.62 },
  ],
  refreshFee: 5,
  _v: 1,
};
