import type { LianliankanConfig } from '@tk/shared';

export const LIANLIANKAN_CONFIG: LianliankanConfig = {
  defaultThemeId: 'fruits',
  defaultDifficultyId: 'easy',
  themes: [
    {
      themeId: 'fruits',
      name: '果蔬',
      items: [
        { id: 'apple', text: '苹果', emoji: '🍎', similarGroup: 'red' },
        { id: 'cherry', text: '樱桃', emoji: '🍒', similarGroup: 'red' },
        { id: 'strawberry', text: '草莓', emoji: '🍓', similarGroup: 'red' },
        { id: 'banana', text: '香蕉', emoji: '🍌', similarGroup: 'yellow' },
        { id: 'lemon', text: '柠檬', emoji: '🍋', similarGroup: 'yellow' },
        { id: 'corn', text: '玉米', emoji: '🌽', similarGroup: 'yellow' },
        { id: 'pear', text: '梨子', emoji: '🍐', similarGroup: 'green' },
        { id: 'kiwi', text: '猕猴桃', emoji: '🥝', similarGroup: 'green' },
        { id: 'grape', text: '葡萄', emoji: '🍇', similarGroup: 'purple' },
        { id: 'eggplant', text: '茄子', emoji: '🍆', similarGroup: 'purple' },
        { id: 'peach', text: '桃子', emoji: '🍑' },
        { id: 'watermelon', text: '西瓜', emoji: '🍉' },
      ],
      similarGroups: [
        { groupId: 'red', itemIds: ['apple', 'cherry', 'strawberry'] },
        { groupId: 'yellow', itemIds: ['banana', 'lemon', 'corn'] },
        { groupId: 'green', itemIds: ['pear', 'kiwi'] },
        { groupId: 'purple', itemIds: ['grape', 'eggplant'] },
      ],
    },
    {
      themeId: 'generals',
      name: '三国武将',
      items: [
        { id: 'liubei', text: '刘备', emoji: '仁', similarGroup: 'shu' },
        { id: 'guanyu', text: '关羽', emoji: '义', similarGroup: 'shu' },
        { id: 'zhangfei', text: '张飞', emoji: '勇', similarGroup: 'shu' },
        { id: 'caocao', text: '曹操', emoji: '魏', similarGroup: 'wei' },
        { id: 'xiahoudun', text: '夏侯惇', emoji: '刚', similarGroup: 'wei' },
        { id: 'zhangliao', text: '张辽', emoji: '突', similarGroup: 'wei' },
        { id: 'sunquan', text: '孙权', emoji: '吴', similarGroup: 'wu' },
        { id: 'zhouyu', text: '周瑜', emoji: '火', similarGroup: 'wu' },
        { id: 'luxun', text: '陆逊', emoji: '连', similarGroup: 'wu' },
        { id: 'lvbu', text: '吕布', emoji: '猛', similarGroup: 'qun' },
        { id: 'diaochan', text: '貂蝉', emoji: '离', similarGroup: 'qun' },
        { id: 'huatuo', text: '华佗', emoji: '医', similarGroup: 'qun' },
      ],
      similarGroups: [
        { groupId: 'shu', itemIds: ['liubei', 'guanyu', 'zhangfei'] },
        { groupId: 'wei', itemIds: ['caocao', 'xiahoudun', 'zhangliao'] },
        { groupId: 'wu', itemIds: ['sunquan', 'zhouyu', 'luxun'] },
        { groupId: 'qun', itemIds: ['lvbu', 'diaochan', 'huatuo'] },
      ],
    },
    {
      themeId: 'office',
      name: '办公用品',
      items: [
        { id: 'sheet', text: '表格', emoji: '表', similarGroup: 'file' },
        { id: 'doc', text: '文档', emoji: '文', similarGroup: 'file' },
        { id: 'slide', text: '幻灯', emoji: '演', similarGroup: 'file' },
        { id: 'pen', text: '钢笔', emoji: '笔', similarGroup: 'tool' },
        { id: 'pencil', text: '铅笔', emoji: '铅', similarGroup: 'tool' },
        { id: 'ruler', text: '直尺', emoji: '尺', similarGroup: 'tool' },
        { id: 'folder', text: '文件夹', emoji: '夹', similarGroup: 'storage' },
        { id: 'box', text: '档案盒', emoji: '盒', similarGroup: 'storage' },
        { id: 'clip', text: '回形针', emoji: '针', similarGroup: 'small' },
        { id: 'staple', text: '订书机', emoji: '订', similarGroup: 'small' },
        { id: 'calendar', text: '日历', emoji: '历' },
        { id: 'printer', text: '打印机', emoji: '印' },
      ],
      similarGroups: [
        { groupId: 'file', itemIds: ['sheet', 'doc', 'slide'] },
        { groupId: 'tool', itemIds: ['pen', 'pencil', 'ruler'] },
        { groupId: 'storage', itemIds: ['folder', 'box'] },
        { groupId: 'small', itemIds: ['clip', 'staple'] },
      ],
    },
  ],
  difficulties: [
    { difficultyId: 'easy', name: '简单', rows: 6, cols: 6, kindCount: 8, timeLimitSec: 180, entryFee: 5, rewardCoins: 8, similarGroupWeight: 0.1 },
    { difficultyId: 'normal', name: '普通', rows: 8, cols: 8, kindCount: 14, timeLimitSec: 150, entryFee: 5, rewardCoins: 15, similarGroupWeight: 0.35 },
    { difficultyId: 'hard', name: '困难', rows: 10, cols: 10, kindCount: 22, timeLimitSec: 120, entryFee: 5, rewardCoins: 30, similarGroupWeight: 0.6 },
  ],
  _v: 1,
};
